# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Authelia installation tasks
  when: authelia_enabled | bool
  tags:
    - setup-all
    - setup-authelia
    - install-all
    - install-authelia
  block:
    - name: Validate Authelia configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Authelia
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Authelia uninstallation tasks
  when: not authelia_enabled | bool
  tags:
    - setup-all
    - setup-authelia
  block:
    - name: Uninstall Authelia
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
