# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Authelia systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ authelia_identifier }}.service"
  register: authelia_service_stat

- name: Uninstall Authelia systemd services and files
  when: authelia_service_stat.stat.exists | bool
  block:
    - name: Ensure Authelia systemd service is stopped
      ansible.builtin.service:
        name: "{{ authelia_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Authelia systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ authelia_identifier }}.service"
        state: absent

    - name: Ensure Authelia path does not exist
      ansible.builtin.file:
        path: "{{ authelia_base_path }}"
        state: absent
